<a href="https://colab.research.google.com/github/BurakAgcakaya/NumpyAssignment/blob/main/Statistics_Assignment_2_ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
import scipy as stats
import pandas as pd

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
samples = np.random.normal(loc=100, scale=15, size=1000)
samples

array([127.36096915,  86.20063651,  89.3882857 , 108.67713826,
       100.93396216,  95.77742761,  92.21231146,  89.16250405,
        98.05534186,  98.57459364,  95.20183313,  63.35007231,
       104.63633929, 104.79244197,  78.66391202,  96.38208179,
        76.70220394,  86.96429531,  97.34282498,  91.97285938,
        97.67684212,  98.97561455,  91.51515304, 118.29061886,
       116.70391713,  64.05312182, 116.31410666,  88.03445387,
        90.05630727, 114.68483414, 114.7344445 , 106.69429395,
       126.70595151, 106.84708242, 103.67429028,  98.0460616 ,
       134.45748051,  72.90830819,  94.74644377,  93.18386014,
        92.42447557, 105.65000436, 121.99660797, 123.53321118,
        84.12170965,  78.61351273, 105.3510195 ,  84.84134887,
        97.24142084, 110.87923645,  88.8165709 , 100.4065048 ,
       108.1945847 ,  70.47799762,  81.71571018, 106.64030293,
        93.38082747,  96.81169737, 103.9767567 ,  79.22920012,
       101.76951507,  88.3079878 ,  87.30932761,  88.83

array([112.41100343,  80.16371216, 105.84075125,  98.60509851,
       108.51272031, 102.17913651,  95.67434825, 107.74338073,
       105.71495432,  97.01871475,  56.37644543, 108.54014777,
       122.6369645 , 125.7018391 , 120.87195254,  87.06729637,
        86.51956127,  91.58128301,  78.81166421,  87.25336854,
       112.07925759, 108.20816939,  85.10350071,  86.23083273,
       101.20169592,  99.49333535,  99.2265054 ,  91.67344377,
       100.27504791, 128.08417228, 107.38938114,  92.90965465,
       102.87248494, 103.71238935,  76.54265397,  80.70989698,
       102.4472072 ,  98.47299141, 108.40803567,  98.59501733,
       102.88686263, 121.38152353,  96.7728495 ,  79.4731193 ,
        89.63279402,  84.70895897, 106.13521798,  88.26750715,
       115.03618212,  96.1782719 ,  79.21193433,  77.20188114,
       103.54474774,  86.50179583,  96.2314896 ,  93.62310746,
        95.88245189,  94.95445612, 107.63264389, 121.42805949,
        99.22675167,  93.76963624,  88.40624446,  98.63

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = samples.mean()
mean

99.39455027464612

In [ ]:
median = np.median(samples)
median

99.12844391494124

In [ ]:
mode = samples.mean() % np.median(samples)
mode

0.26610635970487806

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = samples.argmin()
min

714

In [ ]:
max = samples.argmax()
max

332

In [ ]:
q1 = np.quantile(samples, 0.25)
q1

89.64857651725818

In [ ]:
q3 = np.quantile(samples, 0.75)
q3

108.85418703530675

In [ ]:
iqr = np.quantile(samples, 0.75) - np.quantile(samples, 0.25)
iqr

19.205610518048573

Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
variance

222.00262448334297

In [ ]:
std_dev = np.std(samples)
std_dev

14.899752497385418

Compute the **skewness** and **kurtosis**

In [ ]:
skewness = 3 * (mean - median) / std_dev
skewness

0.05357935168753453

In [ ]:
from scipy.stats import kurtosis

In [ ]:
kurtosis(samples, fisher=False)

3.109464322263569

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = np.corrcoef(x, y)
r

array([[1., 1.],
       [1., 1.]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = np.corrcoef(x, y)
r

array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
from scipy import stats

In [ ]:
rho = stats.spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
df = pd.DataFrame(tips)
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
df.mean()

total_bill    19.785943
tip            2.998279
size           2.569672
dtype: float64

In [ ]:
df.median()

total_bill    17.795
tip            2.900
size           2.000
dtype: float64

In [ ]:
df.mode()

total_bill  tip   sex smoker  day    time  size
0       13.42  2.0  Male     No  Sat  Dinner     2

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
pearsoncorr = tips.corr
pearsoncorr

<bound method DataFrame.corr of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>